version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pacote
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.3.0
    - 11.3.1
    - 11.3.2
  - dependency-name: tap
    versions:
    - 14.11.0
    - 15.0.0
    - 15.0.1
    - 15.0.2
    - 15.0.3
    - 15.0.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: licensee
    versions:
    - 8.1.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
